### PR TITLE
WIP MacOS / Linux support

### PR DESCRIPTION
**Pull request by meunierd**
I finally got something running:

screen shot 2017-11-08 at 4 02 11 pm

xdelta detection is kind of borked right now, and I haven't tried packaging this with pyinstaller yet but it "works"!

Currently running np21.exe under wine because I can't figure out how to get the Retroarch version running.

I've also added a [Pipfile](https://github.com/pypa/pipfile) for **deterministically** managing dependencies.

### CODE REVIEW

**Comment by meunierd** [comment]
I also abstracted out the ndc code into its own package: https://github.com/meunierd/ndcpy/blob/master/ndc/__init__.py -- will publish once I've written a README.

Getting this across the finish line is probably gonna be slow, I'm at home on pat leave so this is being done in the like 20 minute stints that my son decides to sleep.

**Comment by hollowaytape** [comment]
Great! I'll be excited to check this out. Looks like a ton of QOL improvements in there.

I was about to ask how to install ndcpy, will that just be a `pip install ndcpy` thing once you've published it?

**Comment by meunierd** [comment]
It'll be something like:

```
pip install pipenv
pipenv install
pipenv shell --fancy
```

The Pipfile defines what packages are needed to satisfy the application, and the lock file makes sure that everyone gets the exact same versions.

pipenv can also handle a virtualenv workflow for you as well. It's probably the end-all-be-all for application level dependency/environment management, much like bundler is for ruby.

**Comment by meunierd** [comment]
ndcpy is now published!

**Comment by hollowaytape** [comment]
Hmm. Inside or outside the pipenv shell, after installing ndcpy with pip, I haven't been able to import it with `from ndc import NDC`.
`ImportError: No module named 'ndc'`
I followed the steps here and in ndcpy's readme. Is there anything else you or I need to do?

**Comment by meunierd** [comment]
Have you pulled since I rebased? I forgot to commit it before, it should be
okay now. Let me try from a fresh environment.

**Comment by meunierd** [comment]
I forgot the module in the package, will repackage 😬

**Comment by meunierd** [comment]
K it should be good 👍

**Comment by hollowaytape** [comment]
OK. It installs fine now, but once it tries to run NDC, it gets into trouble parsing the output.

```Traceback (most recent call last):
  File "pachy98.py", line 469, in <module>
    disks_in_dir = [Disk(f, ndc_dir=bin_dir) for f in image_paths_in_dir]
  File "pachy98.py", line 469, in <listcomp>
    disks_in_dir = [Disk(f, ndc_dir=bin_dir) for f in image_paths_in_dir]
  File "C:\Users\hollowaytape\romtools\disk.py", line 118, in __init__
    self.ndc = NDC(self.ndc_path)
  File "C:\Users\hollowaytape\.virtualenvs\romtools-5uL6u8ZP\lib\site-packages\ndc\__init__.py", line 65, in __init__
    self.__validate_bin_version()
  File "C:\Users\hollowaytape\.virtualenvs\romtools-5uL6u8ZP\lib\site-packages\ndc\__init__.py", line 69, in __validate_bin_version
    .check_output(self.bin)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 76: invalid start byte
```

I get this in two of my Windows VMs, one using the Shift JIS code page and one using the default English one.

Any idea how to address this? I think I ran into the same thing with `check_output()` before. I think my non-solution was to avoid using `check_output()` to parse output at all, but only to run commands and catch `CalledProcessError`s...

**Comment by meunierd** [comment]
Good old Python encoding issues! My guess is that on nix platforms, the output defaults to UTF-8 and on Windows it's probably shift-jis. If you run:

```
pipenv open ndc
```

it should drop you into an editor for the module and you can replace the `decode` line with `decode('shift-jis')`. If that works, I can add platform detection and use the right decoder. I initially tried decoding from shift-jis on my end but ran into similar errors.

**Comment by hollowaytape** [comment]
Yep! Replacing the three `decode`s with `decode('shift-jis')` works.

It looks like the file timestamp formula could be platform-dependent as well:
```
Traceback (most recent call last):
  File "pachy98.py", line 474, in <module>
    if all([d.find_file(filename) for filename in cfg.all_filenames]):
  File "pachy98.py", line 474, in <listcomp>
    if all([d.find_file(filename) for filename in cfg.all_filenames]):
  File "C:\Users\hollowaytape\code\roms\romtools\disk.py", line 155, in find_file
    results = self.ndc.find_all(self.filename, target_file)
  File "C:\Users\hollowaytape\.virtualenvs\romtools-OgGzTF9v\lib\site-packages\ndc\__init__.py", line 126, in find_all
    return [self.__parse(line) for line in self.__run(cmd)]
  File "C:\Users\hollowaytape\.virtualenvs\romtools-OgGzTF9v\lib\site-packages\ndc\__init__.py", line 126, in <listcomp>
    return [self.__parse(line) for line in self.__run(cmd)]
  File "C:\Users\hollowaytape\.virtualenvs\romtools-OgGzTF9v\lib\site-packages\ndc\__init__.py", line 90, in __parse
    args[-1] = datetime.strptime(args[-1], self.TIMESTAMP_FMT)
  File "c:\python35\Lib\_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "c:\python35\Lib\_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '1990/03/21 18:21:54' does not match format '%a %b %d %H:%M:%S %Y'
```

**Comment by meunierd** [comment]
Which patch/disk(s) are you testing with? I'll try to repro that.

**Comment by hollowaytape** [comment]
I'm testing with `46 Okunen Monogatari - The Sinkaron (J) A user.FDI`, though I'll try some others and see what happens...

Edit: Yep, you should be able to repro it with any disk. Tried the Neo Kobe dump of 46OM, some Rusty dumps, and a CRW dump, and they all do this.

**Comment by meunierd** [comment]
`pipenv install` again after pulling and see if this unpublished ndcpy works

**Comment by hollowaytape** [comment]
Pulled and `pipenv install`ed again, and it breaks in the same `decode()` spot as before. It looks like the latest ndcpy is unchanged except for the version number?

**Comment by meunierd** [comment]
If you `pipenv open ndc` do you see an `import platform`? Maybe the platform detection isn't working and it's still hitting the unix codepath. If it's identical to the old module, maybe just paste in the content of [this file](https://github.com/meunierd/ndcpy/blob/windows-support/ndc/__init__.py)

**Comment by hollowaytape** [comment]
Ah, figured it out. There's still one `decode()` in a Windows branch left, and I opened a PR in the windows-support branch of ndcpy which fixes it. Just patched my copy of E.V.O. with no issues!

I'll continue testing tomorrow to make sure ndcpy works in my current project.

**Comment by meunierd** [comment]
Good catch! I refactored things to get down to a single branch, and updated the pipenv. If everything's good on your end, I'll package a `0.2.0` release. 👍 

In the future I'll try to set up some kind of CI loop to cover these windows cases.

**Comment by hollowaytape** [comment]
Alright! That works, you can package it up.

One thing I found was that ~~ndcpy can't delete or insert files into a disk's subdirectories.~~ I can take a closer look at that tonight and see what I can implement.

Edit: Ah, I see that functionality now. Just need to change my function calls...
Edit2: Alright, there was just one argument missing in Disk.insert(). It's all going swimmingly now.

**Pull request merged**
